id: P007021
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1262
  title: ལུ་ཨི་པའི་དཀྱིལ་ཆོག
  author: ''
  volumes:
    97690b8e521541b89054dbd8b32a8845:
      image_group_id: I1CZ1743
      title: ''
      volume_number: 1
      total_pages: 20
ebook_metadata:
  title: ལུ་ཨི་པའི་དཀྱིལ་ཆོག
  author: ''
  sku: P007021
  cover: cover.jpg
  layers:
  - pagination
